import React, { createContext, useContext, useEffect, useState } from 'react';
import * as profileService from '../services/profileService';

type Language = 'fr' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  loading: boolean;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Traductions
const translations: Record<Language, Record<string, string>> = {
  fr: {
    // Navigation
    'nav.dashboard': 'Tableau de Bord',
    'nav.users': 'Utilisateurs',
    'nav.students': 'Élèves',
    'nav.classes': 'Classes',
    'nav.subjects': 'Matières',
    'nav.schedule': 'Emploi du Temps',
    'nav.evaluations': 'Évaluations',
    'nav.grades': 'Notes',
    'nav.attendance': 'Présences',
    'nav.calendar': 'Calendrier',
    'nav.announcements': 'Annonces',
    'nav.messages': 'Messages',
    'nav.reports': 'Rapports',
    'nav.settings': 'Paramètres',
    'nav.profile': 'Mon Profil',
    
    // Common
    'common.yes': 'Oui',
    'common.no': 'Non',
    'common.loading': 'Chargement...',
    'common.back': 'Retour',
    'common.cancel': 'Annuler',
    'common.save': 'Enregistrer',
    'common.saving': 'Enregistrement...',
    'common.submit': 'Soumettre',
    
    // Teacher
    'teacher.myClasses': 'Mes Classes',
    'teacher.manageClasses': 'Gérer vos classes et vos élèves',
    'teacher.totalClasses': 'Total Classes',
    'teacher.totalStudents': 'Total Élèves',
    'teacher.subjects': 'Matières',
    'teacher.assignedClasses': 'Mes Classes Assignées',
    'teacher.noClassesAssigned': 'Aucune classe assignée',
    'teacher.level': 'Niveau',
    'teacher.year': 'Année',
    'teacher.students': 'élèves',
    'teacher.taughtSubjects': 'Matières enseignées',
    'teacher.attendance': 'Présences',
    'teacher.grades': 'Notes',
    'teacher.details': 'Détails',
    'teacher.information': 'Informations',
    'teacher.studentList': 'Liste des élèves',
    'teacher.noStudents': 'Aucun élève',
    'teacher.selectClassForDetails': 'Sélectionnez une classe pour voir les détails',
    'teacher.markAttendance': 'Marquer les présences des élèves',
    'teacher.class': 'Classe',
    'teacher.selectClass': 'Sélectionner une classe',
    'teacher.date': 'Date',
    'teacher.subject': 'Matière',
    'teacher.optional': 'Optionnel',
    'teacher.allSubjects': 'Toutes les matières',
    'teacher.name': 'Nom et Prénom',
    'teacher.present': 'Présent',
    'teacher.absent': 'Absent',
    'teacher.late': 'Retard',
    'teacher.arrivalTime': 'Heure d\'arrivée',
    'teacher.comments': 'Commentaires (optionnel)',
    'teacher.commentPlaceholder': 'Ex: Maladie, raison personnelle...',
    'teacher.saveAttendance': 'Enregistrer les présences',
    'teacher.saving': 'Enregistrement...',
    'teacher.save': 'Enregistrer',
    'teacher.noStudentsInClass': 'Aucun élève dans cette classe',
    'teacher.selectClassToStart': 'Veuillez sélectionner une classe pour commencer',
    'teacher.attendanceSheet': 'Fiche de Présence',
    'teacher.viewAttendanceStats': 'Consulter les statistiques de présence',
    'teacher.period': 'Période',
    'teacher.today': "Aujourd'hui",
    'teacher.thisWeek': 'Cette semaine',
    'teacher.thisMonth': 'Ce mois',
    'teacher.recentAttendance': 'Présence Récemment Recensée',
    'teacher.globalStatistics': 'Statistique Globale',
    'teacher.presence': 'Présence',
    'teacher.absence': 'Absence',
    'teacher.detailedByClass': 'Détails par Classe',
    'teacher.total': 'Total',
    'teacher.takeAttendance': "Faire l'Appel",
    'teacher.schedule': 'Emploi du Temps',
    'teacher.notifications': 'Notification',
    'teacher.noScheduleToday': 'Aucun cours prévu aujourd\'hui',
    'teacher.viewWeeklySchedule': 'Consulter votre planning hebdomadaire',
    'teacher.noCoursesToday': 'Aucun cours prévu aujourd\'hui',
    'teacher.weeklySchedule': 'Planning Hebdomadaire',
    'teacher.selectDay': 'Sélectionner le jour',
    'teacher.weeklyHours': 'Heures par semaine',
    'teacher.todayCourses': 'Cours aujourd\'hui',
    'teacher.classes': 'Classes',
    'teacher.noScheduleAvailable': 'Aucun emploi du temps disponible. L\'administrateur doit d\'abord générer l\'emploi du temps.',
    'teacher.dashboard': 'Tableau de Bord',
    'teacher.welcome': 'Bienvenue dans votre espace enseignant',
    'teacher.noClasses': 'Aucune classe assignée',
    'teacher.viewClass': 'Voir la classe',
    'teacher.quickActions': 'Actions Rapides',
    'teacher.enterGrades': 'Saisir les notes',
    'teacher.saveEvaluations': 'Enregistrer les évaluations',
    'teacher.gradeBook': 'Carnet de Note',
    'teacher.manageGrades': 'Gérer vos notes et évaluations',
    'teacher.recentActivities': 'ACTIVITÉS RÉCENTES',
    'teacher.gradeNoteCM2': 'Note de la classe de CM2 remplit',
    'teacher.gradeNoteCP': 'Note de la classe de CP remplit',
    'teacher.gradeNoteSIL': 'Note de la classe de SIL remplit',
    'teacher.gradeNoteCE1': 'Note de la classe de CE1 remplit',
    'teacher.twoWeeksAgo': 'il y\'a 2 semaines',
    'teacher.addGrade': 'Ajouter Note',
    'teacher.editGrade': 'Modifier Note',
    'teacher.history': 'Historique',
    'teacher.exerciseBook': 'Mon Cahier d\'exercice',
    'teacher.createManageExercises': 'Créer et gérer vos exercices',
    'teacher.saveAllExercises': 'Enregistrer chacun de vos exercices',
    'teacher.exerciseSaved': 'Exercice enregistré avec succès!',
    'teacher.selectSubject': 'Sélectionner la matière',
    'teacher.settings': 'Paramètres',
    'teacher.title': 'Intitulé',
    'teacher.titlePlaceholder': 'Géologie',
    'teacher.description': 'Description',
    'teacher.document': 'Document',
    'teacher.recentAssignments': 'Vos Récents Devoirs',
    'teacher.noRecentAssignments': 'Aucun devoir récent',
    'teacher.role': 'Enseignant',
    'teacher.gradeNoteClass': 'Note de la classe remplie',
    'teacher.noRecentGrades': 'Aucune note récente',
    'teacher.yesterday': 'Hier',
    'teacher.daysAgo': 'jours',
    'teacher.oneWeekAgo': 'Il y a 1 semaine',
    'teacher.weeksAgo': 'Il y a {weeks} semaines',
    'teacher.errorLoadingGrades': 'Erreur lors du chargement des notes',
    'teacher.noRecentActivities': 'Aucune activité récente',

    // Profile
    'profile.title': 'Profil',
    'profile.subtitle': 'Mettez à jour vos informations personnelles et vos préférences.',
    'profile.personal': 'Informations',
    'profile.security': 'Sécurité',
    'profile.preferences': 'Préférences',
    'profile.personalInfo': 'Informations personnelles',
    'profile.firstName': 'Prénom',
    'profile.lastName': 'Nom',
    'profile.email': 'Email',
    'profile.phone': 'Téléphone',
    'profile.emailReadOnly': 'L\'email ne peut pas être modifié',
    'profile.save': 'Enregistrer',
    'profile.oldPassword': 'Ancien mot de passe',
    'profile.newPassword': 'Nouveau mot de passe',
    'profile.confirmPassword': 'Confirmer le nouveau mot de passe',
    'profile.minPassword': 'Minimum 6 caractères',
    'profile.changePassword': 'Modifier le mot de passe',
    'profile.language': 'Langue de l\'interface',
    'profile.theme': 'Thème',
    'profile.themeLight': 'Clair',
    'profile.themeDark': 'Sombre',
    'profile.themeDescription': 'Le thème est appliqué immédiatement et sauvegardé automatiquement',
    'profile.colorTheme': 'Couleurs de l\'interface Admin',
    'profile.colorThemeDescription': 'Choisissez une palette de couleurs pour personnaliser l\'apparence de la section administration',
    'profile.emailNotifications': 'Notifications email',
    'profile.emailNotificationsDesc': 'Recevoir un résumé hebdomadaire',
    'profile.savePreferences': 'Sauvegarder les préférences',
    'profile.loadError': 'Erreur lors du chargement du profil',
    
    // Color themes
    'theme.blueYellow': 'Bleu & Jaune',
    'theme.greenTeal': 'Vert & Turquoise',
    'theme.purplePink': 'Violet & Rose',
    'theme.orangeRed': 'Orange & Rouge',
    'theme.indigoBlue': 'Indigo & Bleu',
    
    // Dashboard
    'dashboard.title': 'Tableau de Bord',
    'dashboard.subtitle': 'Bienvenue dans votre espace de gestion complète du système',
    'dashboard.superAdmin': 'Super-Administrateur',
    'dashboard.adminAccounts': 'Comptes Administration',
    'dashboard.teachers': 'Enseignants',
    'dashboard.parents': 'Parents',
    'dashboard.students': 'Élèves',
    'dashboard.quickActions': 'Actions Rapides',
    'dashboard.registerStudent': 'Inscrire un élève',
    'dashboard.manageUsers': 'Gérer les utilisateurs',
    'dashboard.manageRoles': 'Gérer les rôles',
    'dashboard.globalView': 'Vue globale',
    'dashboard.userManagement': 'Gestion des Utilisateurs',
    'dashboard.userManagementDesc': 'Créez et gérez tous les utilisateurs du système (Admin, Enseignants, Parents)',
    'dashboard.manageUsersBtn': 'Gérer les Utilisateurs',
    'dashboard.rolesPermissions': 'Rôles et Permissions',
    'dashboard.rolesPermissionsDesc': 'Définissez avec précision les droits d\'accès de chaque membre de l\'administration',
    'dashboard.manageRolesBtn': 'Gérer les Rôles',
    'dashboard.systemView': 'Vue Globale du Système',
    'dashboard.systemViewDesc': 'Accédez à toutes les données et modules du système avec un contrôle total',
    'dashboard.accessSystemView': 'Accéder à la Vue Globale',
    'dashboard.recentActivities': 'Activités Récentes',
    'dashboard.noRecentActivity': 'Aucune activité récente',
    'dashboard.systemReady': 'Le système est prêt',
    'dashboard.adminView': 'Vue Administration',
    'dashboard.teacherView': 'Vue Enseignant',
    
    // Overview
    'overview.title': 'Vue Globale du Système',
    'overview.subtitle': 'Vue d\'ensemble complète de tous les éléments du système',
    'overview.totalUsers': 'Total Utilisateurs',
    'overview.allAccounts': 'Tous les comptes créés',
    'overview.adminAccounts': 'Comptes Administration',
    'overview.adminMembers': 'Membres de l\'administration',
    'overview.teachers': 'Enseignants',
    'overview.activeTeachers': 'Enseignants actifs',
    'overview.parents': 'Parents',
    'overview.registeredFamilies': 'Familles inscrites',
    'overview.students': 'Élèves',
    'overview.registeredStudents': 'Élèves inscrits',
    'overview.quickAccess': 'Accès Rapides',
    'overview.manageUsers': 'Gérer les Utilisateurs',
    'overview.adminAccountsLink': 'Comptes Administration',
    'overview.studentRegistration': 'Inscription Élèves',
    'overview.rolesPermissions': 'Rôles & Permissions',
    'overview.systemStatus': 'État du Système',
    'overview.system': 'Système',
    'overview.operational': 'Opérationnel',
    'overview.database': 'Base de données',
    'overview.connected': 'Connectée',
    'overview.emailServices': 'Services email',
    'overview.configured': 'Configuré',
    'overview.activitySummary': 'Résumé des Activités',
    'overview.activeUsers': 'Utilisateurs actifs',
    'overview.enrollmentRate': 'Taux d\'inscription',
    'overview.loadingStats': 'Chargement des statistiques...',
    
    // Roles & Permissions
    'roles.title': 'Rôles et Permissions',
    'roles.subtitle': 'Définissez les rôles personnalisés et leurs permissions pour l\'administration',
    'roles.count': 'rôle(s)',
    'roles.newRole': 'Nouveau Rôle',
    'roles.createdRoles': 'Rôles Créés',
    'roles.noRoles': 'Aucun rôle personnalisé créé',
    'roles.createFirst': 'Créez votre premier rôle',
    'roles.loading': 'Chargement...',
    'roles.permissions': 'permission(s)',
    'roles.deleteRole': 'Supprimer le rôle',
    'roles.roleDetails': 'Rôle :',
    'roles.noRoleSelected': 'Aucun rôle sélectionné',
    'roles.selectRole': 'Sélectionnez un rôle pour voir ses permissions',
    'roles.createRole': 'Créer un Nouveau Rôle',
    'roles.roleName': 'Nom du Rôle',
    'roles.roleNamePlaceholder': 'Ex: Directeur, Secrétaire, Comptable...',
    'roles.description': 'Description',
    'roles.descriptionPlaceholder': 'Description du rôle et de ses responsabilités...',
    'roles.permissionsLabel': 'Permissions',
    'roles.selectedPermissions': 'sélectionnée(s)',
    'roles.cancel': 'Annuler',
    'roles.create': 'Créer le Rôle',
    'roles.userManagement': 'Gestion des Utilisateurs',
    'roles.studentManagement': 'Gestion des Élèves',
    'roles.academicManagement': 'Gestion Académique',
    'roles.administration': 'Administration',
    'roles.system': 'Système',
    'roles.enabled': '✓ Activée',
    'roles.deleteConfirm': 'Êtes-vous sûr de vouloir supprimer ce rôle ? Les utilisateurs avec ce rôle devront être réassignés.',
    'roles.createError': 'Veuillez sélectionner au moins une permission',
    
    // Users Management
    'users.title': 'Gestion des Utilisateurs et Élèves',
    'users.subtitle': 'Créez et gérez tous les comptes utilisateurs et élèves du système',
    'users.users': 'Utilisateurs',
    'users.students': 'Élèves',
    'users.total': 'Total',
    'users.administration': 'Administration',
    'users.teacher': 'Enseignant',
    'users.parent': 'Parent',
    'users.newUser': 'Nouvel Utilisateur',
    'users.newStudent': 'Nouvel Élève',
    'users.studentsList': 'Liste de tous les élèves inscrits dans le système',
    'users.noUsers': 'Aucun utilisateur créé',
    'users.noUsersByRole': 'Aucun',
    'users.created': 'créé',
    'users.startCreating': 'Commencez par créer votre premier utilisateur',
    'users.user': 'Utilisateur',
    'users.email': 'Email',
    'users.role': 'Rôle',
    'users.creationDate': 'Date de création',
    'users.actions': 'Actions',
    'users.edit': 'Modifier',
    'users.suspend': 'Suspendre',
    'users.delete': 'Supprimer',
    'users.deleteConfirm': 'Êtes-vous sûr de vouloir supprimer cet utilisateur ?',
    'users.suspendConfirm': 'Êtes-vous sûr de vouloir suspendre cet utilisateur ?',
    'users.student': 'Élève',
    'users.birthDate': 'Date de naissance',
    'users.class': 'Classe',
    'users.enrollmentDate': 'Date d\'inscription',
    'users.viewDetails': 'Voir détails',
    'users.noStudents': 'Aucun élève inscrit',
    'users.startRegistering': 'Commencez par inscrire votre premier élève',
    'users.notAssigned': 'Non assigné',
    'users.loadingUsers': 'Chargement des utilisateurs',
    'users.loadingStudents': 'Chargement des élèves',
    'users.createUser': 'Créer un Nouvel Utilisateur',
    'users.firstName': 'Prénom',
    'users.lastName': 'Nom',
    'users.phone': 'Téléphone',
    'users.accountType': 'Type de Compte',
    'users.password': 'Mot de passe',
    'users.passwordHelper': 'Minimum 8 caractères avec majuscule, minuscule et chiffre',
    'users.adminDesc': 'Les comptes Administration peuvent gérer les élèves, classes et valider les notes',
    'users.teacherDesc': 'Les enseignants peuvent saisir les notes et suivre les présences',
    'users.parentDesc': 'Les parents peuvent consulter les résultats de leurs enfants',
    'users.cancel': 'Annuler',
    'users.createAccount': 'Créer le Compte',
    'users.deleteStudentConfirm': 'Êtes-vous sûr de vouloir supprimer cet élève ? Cette action est irréversible.',
    
    // Students Management
    'students.filterByClass': 'Filtrer par classe',
    'students.allClasses': 'Toutes les classes',
    'students.searchByName': 'Rechercher par nom ou prénom',
    'students.searchPlaceholder': 'Entrez un nom ou prénom...',
    'students.showingCount': 'Afficher',
    'students.student': 'élève',
    'students.of': 'sur',
    'students.noStudentFound': 'Aucun élève trouvé',
    'students.noMatchCriteria': 'Aucun élève ne correspond aux critères de recherche.',
    'students.resetFilters': 'Réinitialiser les filtres',
    'students.confirmArchive': 'Êtes-vous sûr de vouloir archiver cet élève ?',
    'students.archivedSuccess': 'Élève archivé avec succès',
    'students.archiveError': 'Erreur lors de la suppression',
    'students.editTitle': 'Modifier un Élève',
    'students.editSubtitle': 'Modifier les informations de l\'élève',
    'students.invalidId': 'ID élève invalide',
    'students.loadError': 'Erreur lors du chargement des données',
    'students.updateSuccess': 'Élève mis à jour avec succès',
    'students.updateError': 'Erreur lors de la mise à jour',
    'students.notFound': 'Élève non trouvé',
    'students.additionalInfo': 'Informations supplémentaires',
    'students.enrollmentDate': 'Date d\'inscription',
    'students.parent': 'Parent',
    'students.currentClass': 'Classe actuelle',
    
    // Student Registration
    'student.title': 'Fiche d\'Inscription d\'un Élève',
    'student.subtitle': 'Remplissez toutes les informations pour inscrire un nouvel élève',
    'student.studentInfo': 'Informations de l\'Élève',
    'student.firstName': 'Prénom',
    'student.lastName': 'Nom',
    'student.birthDate': 'Date de naissance',
    'student.class': 'Classe',
    'student.selectClass': 'Sélectionner une classe',
    'student.loadingClasses': 'Chargement...',
    'student.schoolOrigin': 'École de provenance',
    'student.schoolOriginPlaceholder': 'Nom de l\'école précédente',
    'student.disability': 'Handicap',
    'student.yes': 'Oui',
    'student.no': 'Non',
    'student.disabilityDescription': 'Description du handicap',
    'student.disabilityPlaceholder': 'Décrivez le type de handicap...',
    'student.orphan': 'Orphelin',
    'student.orphanType': 'Type',
    'student.father': 'Père',
    'student.mother': 'Mère',
    'student.parentInfo': 'Informations sur les Parents',
    'student.fatherName': 'Nom',
    'student.fatherContact': 'Contact',
    'student.fatherAddress': 'Domicile',
    'student.motherName': 'Nom',
    'student.motherContact': 'Contact',
    'student.motherAddress': 'Domicile',
    'student.guardian': 'Tuteur/Tutrice',
    'student.guardianName': 'Nom',
    'student.guardianContact': 'Contact',
    'student.authorizedPersons': 'Personnes Autorisées a prendre l\'enfant',
    'student.person1Name': '1. Nom',
    'student.person1Tel': 'Téléphone',
    'student.person2Name': '2. Nom',
    'student.person2Tel': 'Téléphone',
    'student.paymentOption': 'Option de Paiement',
    'student.option1': 'Option 1 : Tous les mois (le 5 du mois)',
    'student.option1Desc': 'Dernière échéance le 05 MARS 2026',
    'student.option2': 'Option 2 : Tous les trimestres',
    'student.option2Desc': 'Dernière échéance le 05 MARS 2026',
    'student.option3': 'Option 3 : Une ou deux tranches (scolarité annuelle)',
    'student.option3Desc': 'Dernière échéance le 05 MARS 2026',
    'student.parentAssociation': 'Association à un Compte Parent',
    'student.parentSearchDesc': 'Recherchez le compte parent existant ou créez-en un nouveau pour associer cet élève',
    'student.parentEmail': 'Email du parent',
    'student.parentEmailPlaceholder': 'parent@example.com',
    'student.search': 'Rechercher',
    'student.parentAutoCreate': 'Si le parent n\'existe pas, il sera créé automatiquement avec cet email',
    'student.cancel': 'Annuler',
    'student.save': 'Enregistrer l\'Inscription',
    'student.saving': 'Enregistrement...',
    'student.searchParent': 'Rechercher un Parent',
    'student.searching': 'Recherche...',
    'student.parentFound': 'Parent trouvé :',
    'student.hasChildren': 'A déjà',
    'student.children': 'enfant(s) inscrit(s)',
    
    // Settings (Parent)
    'settings.appSettings': 'Paramètres de l\'application',
    'settings.managePreferences': 'Gérez vos préférences de sécurité et d\'affichage.',
    'settings.title': 'Paramètres',
    'settings.subtitle': 'Gérer vos paramètres',
    'settings.loadError': 'Erreur lors du chargement des paramètres',
    'settings.appearance': 'Apparence',
    'settings.darkMode': 'Mode Sombre',
    'settings.darkModeDesc': 'Basculer entre le thème clair et sombre.',
    'settings.light': 'Clair',
    'settings.dark': 'Sombre',
    'settings.language': 'Langue',
    'settings.languageDesc': 'Choisissez votre langue d\'interface',
    'settings.security': 'Sécurité du compte',
    'settings.twoFactorStatus': 'Statut de la 2FA',
    'settings.twoFactor': 'Double authentification (2FA)',
    'settings.twoFactorDesc': 'Ajoute une étape de sécurité lors de la connexion.',
    'settings.changePassword': 'Changer le mot de passe',
    'settings.alerts': 'Alertes Importantes',
    'settings.emailAlerts': 'Alertes par Email',
    'settings.emailAlertsDesc': 'Recevoir les bulletins et factures par email.',
    'settings.smsAlerts': 'Alertes SMS (Urgence)',
    'settings.smsAlertsDesc': 'Retards graves ou absence non justifiée.',
    'settings.help': 'Aide & Informations',
    'settings.contactSupport': 'Contacter le support',
    'settings.version': 'Expression d\'Or App - v1.0.2',
    
    // Settings (SuperAdmin)
    'settingsSuperAdmin.title': 'Paramètres Système',
    'settingsSuperAdmin.subtitle': 'Configurez les informations de l\'établissement, les options académiques et les sauvegardes.',
    'settingsSuperAdmin.general': 'Général',
    'settingsSuperAdmin.academic': 'Académique',
    'settingsSuperAdmin.system': 'Système',
    'settingsSuperAdmin.security': 'Sécurité',
    'settingsSuperAdmin.backup': 'Sauvegarde',
    'settingsSuperAdmin.generalInfo': 'Informations générales',
    'settingsSuperAdmin.schoolName': 'Nom de l\'école',
    'settingsSuperAdmin.schoolCode': 'Code d\'établissement',
    'settingsSuperAdmin.address': 'Adresse',
    'settingsSuperAdmin.phone': 'Téléphone',
    'settingsSuperAdmin.email': 'Email',
    'settingsSuperAdmin.director': 'Directeur',
    'settingsSuperAdmin.saveSettings': 'Enregistrer les paramètres',
    'settingsSuperAdmin.academicSettings': 'Paramètres académiques',
    'settingsSuperAdmin.academicDesc': 'Cette section permettra bientôt de configurer les périodes trimestrielles, le barème des notes et les seuils d\'alerte d\'absences. En attendant, vous pouvez gérer ces éléments depuis les onglets "Évaluations" et "Présences".',
    'settingsSuperAdmin.comingSoon': 'À venir',
    'settingsSuperAdmin.comingSoon1': 'Gestion des périodes académiques et des bulletins.',
    'settingsSuperAdmin.comingSoon2': 'Définition des coefficients globaux par matière.',
    'settingsSuperAdmin.comingSoon3': 'Automatisation des notifications d\'absences et retards.',
    'settingsSuperAdmin.systemSettings': 'Paramètres système',
    'settingsSuperAdmin.timezone': 'Fuseau horaire',
    'settingsSuperAdmin.language': 'Langue',
    'settingsSuperAdmin.dateFormat': 'Format de la date',
    'settingsSuperAdmin.saveSystemSettings': 'Enregistrer les paramètres système',
    'settingsSuperAdmin.twoFactorTitle': 'Double authentification (2FA)',
    'settingsSuperAdmin.twoFactorDesc': 'La double authentification ajoute une couche de sécurité supplémentaire à votre compte. À chaque connexion, un code temporaire vous sera envoyé par email que vous devrez entrer en plus de votre mot de passe.',
    'settingsSuperAdmin.twoFactorStatus': 'Statut de la 2FA',
    'settingsSuperAdmin.twoFactorEnabled': '✅ Double authentification activée',
    'settingsSuperAdmin.twoFactorDisabled': '❌ Double authentification désactivée',
    'settingsSuperAdmin.enableTwoFactorDesc': 'Pour activer la 2FA, un code de vérification sera envoyé à votre adresse email. Vous devrez entrer ce code pour finaliser l\'activation.',
    'settingsSuperAdmin.sending': 'Envoi en cours...',
    'settingsSuperAdmin.enable2FA': 'Activer la 2FA',
    'settingsSuperAdmin.codeSent': '📧 Un code de vérification a été envoyé à votre adresse email. Vérifiez votre boîte de réception (et les spams si nécessaire).',
    'settingsSuperAdmin.enterCode': 'Entrez le code de vérification à 6 chiffres :',
    'settingsSuperAdmin.codeValid': 'Le code est valide pendant 10 minutes',
    'settingsSuperAdmin.verifying': 'Vérification...',
    'settingsSuperAdmin.verifyAndEnable': 'Vérifier et activer',
    'settingsSuperAdmin.cancel': 'Annuler',
    'settingsSuperAdmin.twoFactorActiveDesc': '✅ La double authentification est activée. À chaque connexion, vous recevrez un code par email que vous devrez entrer pour accéder à votre compte.',
    'settingsSuperAdmin.disabling': 'Désactivation...',
    'settingsSuperAdmin.disable2FA': 'Désactiver la 2FA',
    'settingsSuperAdmin.disableConfirm': 'Êtes-vous sûr de vouloir désactiver la double authentification ?',
    'settingsSuperAdmin.backupManagement': 'Gestion des sauvegardes',
    'settingsSuperAdmin.backupInfo': 'ℹ Fonctionnalité de sauvegarde à implémenter',
    'settingsSuperAdmin.createBackup': 'Créer une sauvegarde',
    'settingsSuperAdmin.restoreBackup': 'Restaurer une sauvegarde',
    'settingsSuperAdmin.loading': 'Chargement...',
    
    // Sidebar & Navigation
    'sidebar.dashboard': 'Tableau de Bord',
    'sidebar.studentRegistration': 'Inscription Élèves',
    'sidebar.userManagement': 'Gestion Utilisateurs',
    'sidebar.rolesPermissions': 'Rôles & Permissions',
    'sidebar.globalView': 'Vue Globale',
    'sidebar.adminView': 'Vue Administration',
    'sidebar.teacherView': 'Vue Enseignant',
    'sidebar.superAdminView': 'Tableau de Bord Super Admin',
    'sidebar.notifications': 'Notifications',
    'sidebar.messages': 'Messages',
    'sidebar.profile': 'Profil',
    'sidebar.settings': 'Paramètres',
    'sidebar.logout': 'Déconnexion',
    'sidebar.toggleMenu': 'Ouvrir/Fermer le menu',
    
    // Attendance
    'attendance.adminNote': 'Note: Les enseignants enregistrent généralement les présences. Cette section permet à l\'admin de corriger ou compléter les données si nécessaire.',
    
    // Grades
    'grades.fillGrades': 'Remplissage de Notes d\'évaluations',
    'grades.enterGrades': 'Saisir les notes des élèves',
    'grades.class': 'Classe',
    'grades.selectClass': 'Sélectionner la classe',
    'grades.saved': 'Notes enregistrées avec succès',
    'grades.gradingScale': 'Barème de notation',
    'grades.masteryMax': 'Maîtrise maximale (Acquis) 8 à 10 P',
    'grades.masteryMin': 'Maîtrise minimale 5 à 7 P',
    'grades.masteryPartial': 'Maîtrise partielle 1 à 4 P',
    'grades.noMastery': 'Non maîtrise 0 Point',
    'grades.name': 'Nom et Prénom',
    'grades.noStudents': 'Aucun élève dans cette classe',
    'grades.selectClassToStart': 'Veuillez sélectionner une classe pour commencer',
    'grades.saving': 'Enregistrement...',
    'grades.save': 'Enregistrer',
    
    // Fees
    'fees.title': 'Gestion des frais',
    'fees.subtitle': 'Suivez les paiements, relancez les familles et exportez les relevés.',
    'fees.totalAmount': 'Montant total',
    'fees.paid': 'Payés',
    'fees.pending': 'En attente',
    'fees.paymentHistory': 'Historique des paiements',
    'fees.filterByClass': 'Filtrer par classe',
    'fees.allClasses': 'Toutes les classes',
    'fees.searchByName': 'Rechercher par nom',
    'fees.searchPlaceholder': 'Nom ou prénom...',
    'fees.filterByStatus': 'Filtrer par statut',
    'fees.allStatuses': 'Tous les statuts',
    'fees.overdue': 'En retard',
    'fees.noPayments': 'Aucun paiement trouvé',
    'fees.student': 'Élève',
    'fees.class': 'Classe',
    'fees.installment': 'Tranche',
    'fees.installmentNumber': 'Tranche',
    'fees.amount': 'Montant',
    'fees.dueDate': 'Date limite',
    'fees.paidDate': 'Date de paiement',
    'fees.status': 'Statut',
    'fees.actions': 'Actions',
    'fees.update': 'Modifier',
    'fees.record': 'Enregistrer',
    'fees.export': 'Exporter les relevés',
    'fees.exportFeature': 'Fonctionnalité d\'export à implémenter',
    'fees.sendReminder': 'Envoyer un rappel',
    'fees.reminderFeature': 'Fonctionnalité de rappel à implémenter',
    'fees.updatePayment': 'Modifier le paiement',
    'fees.recordPayment': 'Enregistrer un paiement',
    'fees.paymentMethod': 'Méthode de paiement',
    'fees.selectMethod': 'Sélectionner...',
    'fees.bank': 'Banque',
    'fees.cash': 'Espèces',
    'fees.check': 'Chèque',
    'fees.mobileMoney': 'Mobile Money',
    'fees.receiptNumber': 'Numéro de reçu',
    'fees.receiptPlaceholder': 'Numéro du reçu bancaire...',
    'fees.notes': 'Notes',
    'fees.notesPlaceholder': 'Notes supplémentaires...',
    'fees.viewTable': 'Tableau',
    'fees.viewByStudent': 'Par élève',
    'fees.viewCalendar': 'Calendrier',
    'fees.today': "Aujourd'hui",
    'fees.more': 'autres',
    
    // Bulletins
    'bulletins.title': 'Génération des Bulletins',
    'bulletins.subtitle': 'Générez et imprimez les bulletins scolaires des élèves',
    'bulletins.filters': 'Filtres de recherche',
    'bulletins.filterByClass': 'Filtrer par classe',
    'bulletins.allClasses': 'Toutes les classes',
    'bulletins.searchByName': 'Rechercher par nom ou prénom',
    'bulletins.searchPlaceholder': 'Nom ou prénom...',
    'bulletins.studentsList': 'Liste des élèves',
    'bulletins.student': 'élève',
    'bulletins.class': 'Classe',
    'bulletins.level': 'Niveau',
    'bulletins.actions': 'Actions',
    'bulletins.generate': 'Générer le bulletin',
    'bulletins.bulletinOf': 'Bulletin de',
    'bulletins.print': 'Imprimer',
    'bulletins.noStudents': 'Aucun élève trouvé',
    'bulletins.noMatchCriteria': 'Aucun élève ne correspond aux critères de recherche.',
  },
  en: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.users': 'Users',
    'nav.students': 'Students',
    'nav.classes': 'Classes',
    'nav.subjects': 'Subjects',
    'nav.schedule': 'Schedule',
    'nav.evaluations': 'Evaluations',
    'nav.grades': 'Grades',
    'nav.attendance': 'Attendance',
    'nav.calendar': 'Calendar',
    'nav.announcements': 'Announcements',
    'nav.messages': 'Messages',
    'nav.reports': 'Reports',
    'nav.settings': 'Settings',
    'nav.profile': 'My Profile',
    
    // Common
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.loading': 'Loading...',
    'common.back': 'Back',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.saving': 'Saving...',
    'common.submit': 'Submit',
    
    // Teacher
    'teacher.myClasses': 'My Classes',
    'teacher.manageClasses': 'Manage your classes and students',
    'teacher.totalClasses': 'Total Classes',
    'teacher.totalStudents': 'Total Students',
    'teacher.subjects': 'Subjects',
    'teacher.assignedClasses': 'My Assigned Classes',
    'teacher.noClassesAssigned': 'No classes assigned',
    'teacher.level': 'Level',
    'teacher.year': 'Year',
    'teacher.students': 'students',
    'teacher.taughtSubjects': 'Taught Subjects',
    'teacher.attendance': 'Attendance',
    'teacher.grades': 'Grades',
    'teacher.details': 'Details',
    'teacher.information': 'Information',
    'teacher.studentList': 'Student List',
    'teacher.noStudents': 'No students',
    'teacher.selectClassForDetails': 'Select a class to see details',
    'teacher.markAttendance': 'Mark student attendance',
    'teacher.class': 'Class',
    'teacher.selectClass': 'Select a class',
    'teacher.date': 'Date',
    'teacher.subject': 'Subject',
    'teacher.optional': 'Optional',
    'teacher.allSubjects': 'All subjects',
    'teacher.name': 'Name',
    'teacher.present': 'Present',
    'teacher.absent': 'Absent',
    'teacher.late': 'Late',
    'teacher.arrivalTime': 'Arrival Time',
    'teacher.comments': 'Comments (optional)',
    'teacher.commentPlaceholder': 'Ex: Illness, personal reason...',
    'teacher.saveAttendance': 'Save attendance',
    'teacher.saving': 'Saving...',
    'teacher.save': 'Save',
    'teacher.noStudentsInClass': 'No students in this class',
    'teacher.selectClassToStart': 'Please select a class to start',
    'teacher.attendanceSheet': 'Attendance Sheet',
    'teacher.viewAttendanceStats': 'View attendance statistics',
    'teacher.period': 'Period',
    'teacher.today': 'Today',
    'teacher.thisWeek': 'This week',
    'teacher.thisMonth': 'This month',
    'teacher.recentAttendance': 'Recently Recorded Attendance',
    'teacher.globalStatistics': 'Global Statistics',
    'teacher.presence': 'Presence',
    'teacher.absence': 'Absence',
    'teacher.detailedByClass': 'Details by Class',
    'teacher.total': 'Total',
    'teacher.takeAttendance': 'Take Attendance',
    'teacher.schedule': 'Schedule',
    'teacher.noScheduleToday': 'No courses scheduled today',
    'teacher.viewWeeklySchedule': 'View your weekly schedule',
    'teacher.noCoursesToday': 'No courses scheduled today',
    'teacher.weeklySchedule': 'Weekly Schedule',
    'teacher.selectDay': 'Select day',
    'teacher.weeklyHours': 'Hours per week',
    'teacher.todayCourses': 'Courses today',
    'teacher.classes': 'Classes',
    'teacher.noScheduleAvailable': 'No schedule available. The administrator must first generate the schedule.',
    'teacher.dashboard': 'Dashboard',
    'teacher.welcome': 'Welcome to your teacher space',
    'teacher.noClasses': 'No classes assigned',
    'teacher.viewClass': 'View class',
    'teacher.quickActions': 'Quick Actions',
    'teacher.enterGrades': 'Enter grades',
    'teacher.saveEvaluations': 'Save evaluations',
    'teacher.gradeBook': 'Grade Book',
    'teacher.manageGrades': 'Manage your grades and evaluations',
    'teacher.recentActivities': 'RECENT ACTIVITIES',
    'teacher.gradeNoteCM2': 'CM2 class grade filled',
    'teacher.gradeNoteCP': 'CP class grade filled',
    'teacher.gradeNoteSIL': 'SIL class grade filled',
    'teacher.gradeNoteCE1': 'CE1 class grade filled',
    'teacher.twoWeeksAgo': '2 weeks ago',
    'teacher.addGrade': 'Add Grade',
    'teacher.editGrade': 'Edit Grade',
    'teacher.history': 'History',
    'teacher.exerciseBook': 'My Exercise Book',
    'teacher.createManageExercises': 'Create and manage your exercises',
    'teacher.saveAllExercises': 'Save all your exercises',
    'teacher.exerciseSaved': 'Exercise saved successfully!',
    'teacher.selectSubject': 'Select subject',
    'teacher.settings': 'Settings',
    'teacher.title': 'Title',
    'teacher.titlePlaceholder': 'Geology',
    'teacher.description': 'Description',
    'teacher.document': 'Document',
    'teacher.recentAssignments': 'Your Recent Assignments',
    'teacher.noRecentAssignments': 'No recent assignments',
    'teacher.role': 'Teacher',
    'teacher.gradeNoteClass': 'Grade note for class {className}',
    'teacher.noRecentGrades': 'No recent grades',
    'teacher.yesterday': 'Yesterday',
    'teacher.daysAgo': 'days ago',
    'teacher.oneWeekAgo': '1 week ago',
    'teacher.weeksAgo': 'weeks ago',
    'teacher.errorLoadingGrades': 'Error loading grades',
    'teacher.noRecentActivities': 'No recent activities',

    // Profile
    'profile.title': 'Administrator Profile',
    'profile.subtitle': 'Update your personal information and preferences.',
    'profile.personal': 'Information',
    'profile.security': 'Security',
    'profile.preferences': 'Preferences',
    'profile.personalInfo': 'Personal Information',
    'profile.firstName': 'First Name',
    'profile.lastName': 'Last Name',
    'profile.email': 'Email',
    'profile.phone': 'Phone',
    'profile.emailReadOnly': 'Email cannot be modified',
    'profile.save': 'Save',
    'profile.oldPassword': 'Old Password',
    'profile.newPassword': 'New Password',
    'profile.confirmPassword': 'Confirm New Password',
    'profile.minPassword': 'Minimum 6 characters',
    'profile.changePassword': 'Change Password',
    'profile.language': 'Interface Language',
    'profile.theme': 'Theme',
    'profile.themeLight': 'Light',
    'profile.themeDark': 'Dark',
    'profile.themeDescription': 'Theme is applied immediately and saved automatically',
    'profile.colorTheme': 'Admin Interface Colors',
    'profile.colorThemeDescription': 'Choose a color palette to customize the appearance of the administration section',
    'profile.emailNotifications': 'Email Notifications',
    'profile.emailNotificationsDesc': 'Receive a weekly summary',
    'profile.savePreferences': 'Save Preferences',
    'profile.loadError': 'Error loading profile',
    
    // Color themes
    'theme.blueYellow': 'Blue & Yellow',
    'theme.greenTeal': 'Green & Teal',
    'theme.purplePink': 'Purple & Pink',
    'theme.orangeRed': 'Orange & Red',
    'theme.indigoBlue': 'Indigo & Blue',
    
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.subtitle': 'Welcome to your complete system management space',
    'dashboard.superAdmin': 'Super Administrator',
    'dashboard.adminAccounts': 'Administration Accounts',
    'dashboard.teachers': 'Teachers',
    'dashboard.parents': 'Parents',
    'dashboard.students': 'Students',
    'dashboard.quickActions': 'Quick Actions',
    'dashboard.registerStudent': 'Register a student',
    'dashboard.manageUsers': 'Manage users',
    'dashboard.manageRoles': 'Manage roles',
    'dashboard.globalView': 'Global view',
    'dashboard.userManagement': 'User Management',
    'dashboard.userManagementDesc': 'Create and manage all system users (Admin, Teachers, Parents)',
    'dashboard.manageUsersBtn': 'Manage Users',
    'dashboard.rolesPermissions': 'Roles & Permissions',
    'dashboard.rolesPermissionsDesc': 'Precisely define access rights for each administration member',
    'dashboard.manageRolesBtn': 'Manage Roles',
    'dashboard.systemView': 'System Global View',
    'dashboard.systemViewDesc': 'Access all system data and modules with full control',
    'dashboard.accessSystemView': 'Access Global View',
    'dashboard.recentActivities': 'Recent Activities',
    'dashboard.noRecentActivity': 'No recent activity',
    'dashboard.systemReady': 'System is ready',
    
    // Overview
    'overview.title': 'System Global View',
    'overview.subtitle': 'Complete overview of all system elements',
    'overview.totalUsers': 'Total Users',
    'overview.allAccounts': 'All created accounts',
    'overview.adminAccounts': 'Administration Accounts',
    'overview.adminMembers': 'Administration members',
    'overview.teachers': 'Teachers',
    'overview.activeTeachers': 'Active teachers',
    'overview.parents': 'Parents',
    'overview.registeredFamilies': 'Registered families',
    'overview.students': 'Students',
    'overview.registeredStudents': 'Registered students',
    'overview.quickAccess': 'Quick Access',
    'overview.manageUsers': 'Manage Users',
    'overview.adminAccountsLink': 'Administration Accounts',
    'overview.studentRegistration': 'Student Registration',
    'overview.rolesPermissions': 'Roles & Permissions',
    'overview.systemStatus': 'System Status',
    'overview.system': 'System',
    'overview.operational': 'Operational',
    'overview.database': 'Database',
    'overview.connected': 'Connected',
    'overview.emailServices': 'Email services',
    'overview.configured': 'Configured',
    'overview.activitySummary': 'Activity Summary',
    'overview.activeUsers': 'Active users',
    'overview.enrollmentRate': 'Enrollment rate',
    'overview.loadingStats': 'Loading statistics...',
    
    // Roles & Permissions
    'roles.title': 'Roles & Permissions',
    'roles.subtitle': 'Define custom roles and their permissions for administration',
    'roles.count': 'role(s)',
    'roles.newRole': 'New Role',
    'roles.createdRoles': 'Created Roles',
    'roles.noRoles': 'No custom roles created',
    'roles.createFirst': 'Create your first role',
    'roles.loading': 'Loading...',
    'roles.permissions': 'permission(s)',
    'roles.deleteRole': 'Delete role',
    'roles.roleDetails': 'Role:',
    'roles.noRoleSelected': 'No role selected',
    'roles.selectRole': 'Select a role to see its permissions',
    'roles.createRole': 'Create a New Role',
    'roles.roleName': 'Role Name',
    'roles.roleNamePlaceholder': 'Ex: Director, Secretary, Accountant...',
    'roles.description': 'Description',
    'roles.descriptionPlaceholder': 'Role description and responsibilities...',
    'roles.permissionsLabel': 'Permissions',
    'roles.selectedPermissions': 'selected',
    'roles.cancel': 'Cancel',
    'roles.create': 'Create Role',
    'roles.userManagement': 'User Management',
    'roles.studentManagement': 'Student Management',
    'roles.academicManagement': 'Academic Management',
    'roles.administration': 'Administration',
    'roles.system': 'System',
    'roles.enabled': '✓ Enabled',
    'roles.deleteConfirm': 'Are you sure you want to delete this role? Users with this role will need to be reassigned.',
    'roles.createError': 'Please select at least one permission',
    
    // Users Management
    'users.title': 'Users and Students Management',
    'users.subtitle': 'Create and manage all user and student accounts in the system',
    'users.users': 'Users',
    'users.students': 'Students',
    'users.total': 'Total',
    'users.administration': 'Administration',
    'users.teacher': 'Teacher',
    'users.parent': 'Parent',
    'users.newUser': 'New User',
    'users.newStudent': 'New Student',
    'users.studentsList': 'List of all students enrolled in the system',
    'users.noUsers': 'No users created',
    'users.noUsersByRole': 'No',
    'users.created': 'created',
    'users.startCreating': 'Start by creating your first user',
    'users.user': 'User',
    'users.email': 'Email',
    'users.role': 'Role',
    'users.creationDate': 'Creation date',
    'users.actions': 'Actions',
    'users.edit': 'Edit',
    'users.suspend': 'Suspend',
    'users.delete': 'Delete',
    'users.deleteConfirm': 'Are you sure you want to delete this user?',
    'users.suspendConfirm': 'Are you sure you want to suspend this user?',
    'users.student': 'Student',
    'users.birthDate': 'Date of birth',
    'users.class': 'Class',
    'users.enrollmentDate': 'Enrollment date',
    'users.viewDetails': 'View details',
    'users.noStudents': 'No students enrolled',
    'users.startRegistering': 'Start by enrolling your first student',
    'users.notAssigned': 'Not assigned',
    'users.loadingUsers': 'Loading users',
    'users.loadingStudents': 'Loading students',
    'users.createUser': 'Create a New User',
    'users.firstName': 'First Name',
    'users.lastName': 'Last Name',
    'users.phone': 'Phone',
    'users.accountType': 'Account Type',
    'users.password': 'Password',
    'users.passwordHelper': 'Minimum 8 characters with uppercase, lowercase and number',
    'users.adminDesc': 'Administration accounts can manage students, classes and validate grades',
    'users.teacherDesc': 'Teachers can enter grades and track attendance',
    'users.parentDesc': 'Parents can view their children\'s results',
    'users.cancel': 'Cancel',
    'users.createAccount': 'Create Account',
    'users.deleteStudentConfirm': 'Are you sure you want to delete this student? This action is irreversible.',
    
    // Students Management
    'students.filterByClass': 'Filter by class',
    'students.allClasses': 'All classes',
    'students.searchByName': 'Search by name or first name',
    'students.searchPlaceholder': 'Enter a name or first name...',
    'students.showingCount': 'Showing',
    'students.student': 'student',
    'students.of': 'of',
    'students.noStudentFound': 'No student found',
    'students.noMatchCriteria': 'No student matches the search criteria.',
    'students.resetFilters': 'Reset filters',
    'students.confirmArchive': 'Are you sure you want to archive this student?',
    'students.archivedSuccess': 'Student archived successfully',
    'students.archiveError': 'Error during deletion',
    'students.editTitle': 'Edit Student',
    'students.editSubtitle': 'Modify student information',
    'students.invalidId': 'Invalid student ID',
    'students.loadError': 'Error loading data',
    'students.updateSuccess': 'Student updated successfully',
    'students.updateError': 'Error during update',
    'students.notFound': 'Student not found',
    'students.additionalInfo': 'Additional Information',
    'students.enrollmentDate': 'Enrollment Date',
    'students.parent': 'Parent',
    'students.currentClass': 'Current Class',
    
    // Student Registration
    'student.title': 'Student Registration Form',
    'student.subtitle': 'Fill in all information to register a new student',
    'student.studentInfo': 'Student Information',
    'student.firstName': 'First Name',
    'student.lastName': 'Last Name',
    'student.birthDate': 'Date of birth',
    'student.class': 'Class',
    'student.selectClass': 'Select a class',
    'student.loadingClasses': 'Loading...',
    'student.schoolOrigin': 'School of origin',
    'student.schoolOriginPlaceholder': 'Name of previous school',
    'student.disability': 'Disability',
    'student.yes': 'Yes',
    'student.no': 'No',
    'student.disabilityDescription': 'Disability description',
    'student.disabilityPlaceholder': 'Describe the type of disability...',
    'student.orphan': 'Orphan',
    'student.orphanType': 'Type',
    'student.father': 'Father',
    'student.mother': 'Mother',
    'student.parentInfo': 'Parent Information',
    'student.fatherName': 'Name',
    'student.fatherContact': 'Contact',
    'student.fatherAddress': 'Address',
    'student.motherName': 'Name',
    'student.motherContact': 'Contact',
    'student.motherAddress': 'Address',
    'student.guardian': 'Guardian',
    'student.guardianName': 'Name',
    'student.guardianContact': 'Contact',
    'student.authorizedPersons': 'Authorized Persons',
    'student.person1Name': '1. Name',
    'student.person1Tel': 'Phone',
    'student.person2Name': '2. Name',
    'student.person2Tel': 'Phone',
    'student.paymentOption': 'Payment Option',
    'student.option1': 'Option 1: Monthly (on the 5th of the month)',
    'student.option1Desc': 'Last due date March 05, 2026',
    'student.option2': 'Option 2: Quarterly',
    'student.option2Desc': 'Last due date March 05, 2026',
    'student.option3': 'Option 3: One or two installments (annual tuition)',
    'student.option3Desc': 'Last due date March 05, 2026',
    'student.parentAssociation': 'Association with Parent Account',
    'student.parentSearchDesc': 'Search for existing parent account or create a new one to associate this student',
    'student.parentEmail': 'Parent email',
    'student.parentEmailPlaceholder': 'parent@example.com',
    'student.search': 'Search',
    'student.parentAutoCreate': 'If the parent does not exist, they will be automatically created with this email',
    'student.cancel': 'Cancel',
    'student.save': 'Save Registration',
    'student.saving': 'Saving...',
    'student.searchParent': 'Search for a Parent',
    'student.searching': 'Searching...',
    'student.parentFound': 'Parent found:',
    'student.hasChildren': 'Already has',
    'student.children': 'child(ren) enrolled',
    
    // Settings (Parent)
    'settings.appSettings': 'Application Settings',
    'settings.managePreferences': 'Manage your security and display preferences.',
    'settings.title': 'Settings',
    'settings.subtitle': 'Manage your settings',
    'settings.loadError': 'Error loading settings',
    'settings.appearance': 'Appearance',
    'settings.darkMode': 'Dark Mode',
    'settings.darkModeDesc': 'Toggle between light and dark theme.',
    'settings.light': 'Light',
    'settings.dark': 'Dark',
    'settings.language': 'Language',
    'settings.languageDesc': 'Choose your interface language',
    'settings.security': 'Account Security',
    'settings.twoFactorStatus': '2FA Status',
    'settings.twoFactor': 'Two-Factor Authentication (2FA)',
    'settings.twoFactorDesc': 'Adds an extra security step during login.',
    'settings.changePassword': 'Change password',
    'settings.alerts': 'Important Alerts',
    'settings.emailAlerts': 'Email Alerts',
    'settings.emailAlertsDesc': 'Receive reports and invoices by email.',
    'settings.smsAlerts': 'SMS Alerts (Emergency)',
    'settings.smsAlertsDesc': 'Serious delays or unexcused absence.',
    'settings.help': 'Help & Information',
    'settings.contactSupport': 'Contact support',
    'settings.version': 'Expression d\'Or App - v1.0.2',
    
    // Settings (SuperAdmin)
    'settingsSuperAdmin.title': 'System Settings',
    'settingsSuperAdmin.subtitle': 'Configure school information, academic options and backups.',
    'settingsSuperAdmin.general': 'General',
    'settingsSuperAdmin.academic': 'Academic',
    'settingsSuperAdmin.system': 'System',
    'settingsSuperAdmin.security': 'Security',
    'settingsSuperAdmin.backup': 'Backup',
    'settingsSuperAdmin.generalInfo': 'General Information',
    'settingsSuperAdmin.schoolName': 'School Name',
    'settingsSuperAdmin.schoolCode': 'School Code',
    'settingsSuperAdmin.address': 'Address',
    'settingsSuperAdmin.phone': 'Phone',
    'settingsSuperAdmin.email': 'Email',
    'settingsSuperAdmin.director': 'Director',
    'settingsSuperAdmin.saveSettings': 'Save Settings',
    'settingsSuperAdmin.academicSettings': 'Academic Settings',
    'settingsSuperAdmin.academicDesc': 'This section will soon allow you to configure quarterly periods, grading scales and absence alert thresholds. In the meantime, you can manage these items from the "Evaluations" and "Attendance" tabs.',
    'settingsSuperAdmin.comingSoon': 'Coming Soon',
    'settingsSuperAdmin.comingSoon1': 'Management of academic periods and report cards.',
    'settingsSuperAdmin.comingSoon2': 'Definition of global coefficients by subject.',
    'settingsSuperAdmin.comingSoon3': 'Automation of absence and delay notifications.',
    'settingsSuperAdmin.systemSettings': 'System Settings',
    'settingsSuperAdmin.timezone': 'Timezone',
    'settingsSuperAdmin.language': 'Language',
    'settingsSuperAdmin.dateFormat': 'Date Format',
    'settingsSuperAdmin.saveSystemSettings': 'Save System Settings',
    'settingsSuperAdmin.twoFactorTitle': 'Two-Factor Authentication (2FA)',
    'settingsSuperAdmin.twoFactorDesc': 'Two-factor authentication adds an extra layer of security to your account. At each login, a temporary code will be sent to you by email that you will need to enter in addition to your password.',
    'settingsSuperAdmin.twoFactorStatus': '2FA Status',
    'settingsSuperAdmin.twoFactorEnabled': '✅ Two-factor authentication enabled',
    'settingsSuperAdmin.twoFactorDisabled': '❌ Two-factor authentication disabled',
    'settingsSuperAdmin.enableTwoFactorDesc': 'To enable 2FA, a verification code will be sent to your email address. You will need to enter this code to finalize activation.',
    'settingsSuperAdmin.sending': 'Sending...',
    'settingsSuperAdmin.enable2FA': 'Enable 2FA',
    'settingsSuperAdmin.codeSent': '📧 A verification code has been sent to your email address. Check your inbox (and spam if necessary).',
    'settingsSuperAdmin.enterCode': 'Enter the 6-digit verification code:',
    'settingsSuperAdmin.codeValid': 'The code is valid for 10 minutes',
    'settingsSuperAdmin.verifying': 'Verifying...',
    'settingsSuperAdmin.verifyAndEnable': 'Verify and Enable',
    'settingsSuperAdmin.cancel': 'Cancel',
    'settingsSuperAdmin.twoFactorActiveDesc': '✅ Two-factor authentication is enabled. At each login, you will receive a code by email that you will need to enter to access your account.',
    'settingsSuperAdmin.disabling': 'Disabling...',
    'settingsSuperAdmin.disable2FA': 'Désactiver la 2FA',
    'settingsSuperAdmin.disableConfirm': 'Are you sure you want to disable two-factor authentication?',
    'settingsSuperAdmin.backupManagement': 'Backup Management',
    'settingsSuperAdmin.backupInfo': 'ℹ Backup feature to be implemented',
    'settingsSuperAdmin.createBackup': 'Create Backup',
    'settingsSuperAdmin.restoreBackup': 'Restore Backup',
    'settingsSuperAdmin.loading': 'Loading...',
    
    // Sidebar & Navigation
    'sidebar.dashboard': 'Dashboard',
    'sidebar.studentRegistration': 'Student Registration',
    'sidebar.userManagement': 'User Management',
    'sidebar.rolesPermissions': 'Roles & Permissions',
    'sidebar.globalView': 'Global View',
    'sidebar.adminView': 'Administration View',
    'sidebar.teacherView': 'Teacher View',
    'sidebar.messages': 'Messages',
    'sidebar.notifications': 'Notifications',
    'sidebar.superAdminView': 'Super Admin Dashboard',
    'sidebar.profile': 'Profile',
    'sidebar.settings': 'Settings',
    'sidebar.logout': 'Logout',
    'sidebar.toggleMenu': 'Open/Close menu',
    
    // Attendance
    'attendance.adminNote': 'Note: Teachers usually record attendance. This section allows the admin to correct or complete data if necessary.',
    
    // Grades
    'grades.fillGrades': 'Fill Evaluation Grades',
    'grades.enterGrades': 'Enter student grades',
    'grades.class': 'Class',
    'grades.selectClass': 'Select class',
    'grades.saved': 'Grades saved successfully',
    'grades.gradingScale': 'Grading scale',
    'grades.masteryMax': 'Maximum mastery (Acquired) 8 to 10 P',
    'grades.masteryMin': 'Minimum mastery 5 to 7 P',
    'grades.masteryPartial': 'Partial mastery 1 to 4 P',
    'grades.noMastery': 'No mastery 0 Point',
    'grades.name': 'Name',
    'grades.noStudents': 'No students in this class',
    'grades.selectClassToStart': 'Please select a class to start',
    'grades.saving': 'Saving...',
    'grades.save': 'Save',
    
    // Fees
    'fees.title': 'Fee Management',
    'fees.subtitle': 'Track payments, send reminders to families and export statements.',
    'fees.totalAmount': 'Total Amount',
    'fees.paid': 'Paid',
    'fees.pending': 'Pending',
    'fees.paymentHistory': 'Payment History',
    'fees.filterByClass': 'Filter by class',
    'fees.allClasses': 'All classes',
    'fees.searchByName': 'Search by name',
    'fees.searchPlaceholder': 'First or last name...',
    'fees.filterByStatus': 'Filter by status',
    'fees.allStatuses': 'All statuses',
    'fees.overdue': 'Overdue',
    'fees.noPayments': 'No payments found',
    'fees.student': 'Student',
    'fees.class': 'Class',
    'fees.installment': 'Installment',
    'fees.installmentNumber': 'Installment',
    'fees.amount': 'Amount',
    'fees.dueDate': 'Due Date',
    'fees.paidDate': 'Payment Date',
    'fees.status': 'Status',
    'fees.actions': 'Actions',
    'fees.update': 'Update',
    'fees.record': 'Record',
    'fees.export': 'Export statements',
    'fees.exportFeature': 'Export feature to be implemented',
    'fees.sendReminder': 'Send reminder',
    'fees.reminderFeature': 'Reminder feature to be implemented',
    'fees.updatePayment': 'Update Payment',
    'fees.recordPayment': 'Record Payment',
    'fees.paymentMethod': 'Payment Method',
    'fees.selectMethod': 'Select...',
    'fees.bank': 'Bank',
    'fees.cash': 'Cash',
    'fees.check': 'Check',
    'fees.mobileMoney': 'Mobile Money',
    'fees.receiptNumber': 'Receipt Number',
    'fees.receiptPlaceholder': 'Bank receipt number...',
    'fees.notes': 'Notes',
    'fees.notesPlaceholder': 'Additional notes...',
    'fees.viewTable': 'Table',
    'fees.viewByStudent': 'By Student',
    'fees.viewCalendar': 'Calendar',
    'fees.today': 'Today',
    'fees.more': 'more',
    
    // Bulletins
    'bulletins.title': 'Report Cards Generation',
    'bulletins.subtitle': 'Generate and print student report cards',
    'bulletins.filters': 'Search filters',
    'bulletins.filterByClass': 'Filter by class',
    'bulletins.allClasses': 'All classes',
    'bulletins.searchByName': 'Search by name or first name',
    'bulletins.searchPlaceholder': 'Name or first name...',
    'bulletins.studentsList': 'Students list',
    'bulletins.student': 'student',
    'bulletins.class': 'Class',
    'bulletins.level': 'Level',
    'bulletins.actions': 'Actions',
    'bulletins.generate': 'Generate report card',
    'bulletins.bulletinOf': 'Report card of',
    'bulletins.print': 'Print',
    'bulletins.noStudents': 'No students found',
    'bulletins.noMatchCriteria': 'No students match the search criteria.',
  },
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>('fr');
  const [loading, setLoading] = useState(true);

  // Charger la langue depuis le backend ou localStorage
  useEffect(() => {
    const loadLanguage = async () => {
      // Vérifier si l'utilisateur est authentifié
      const token = localStorage.getItem('token');
      if (!token) {
        // Pas de token, utiliser localStorage ou valeur par défaut
        const savedLanguage = localStorage.getItem('language');
        const initialLanguage = (savedLanguage === 'fr' || savedLanguage === 'en') ? savedLanguage : 'fr';
        setLanguageState(initialLanguage);
        setLoading(false);
        return;
      }

      try {
        const profile = await profileService.getCurrentUser();
        if (profile.language && (profile.language === 'fr' || profile.language === 'en')) {
          setLanguageState(profile.language);
          localStorage.setItem('language', profile.language);
          setLoading(false);
          return;
        }
      } catch (err) {
        // Erreur (non authentifié, etc.), utiliser localStorage
        console.warn('Impossible de charger la langue depuis le backend:', err);
      }

      // Fallback sur localStorage
      const savedLanguage = localStorage.getItem('language');
      const initialLanguage = (savedLanguage === 'fr' || savedLanguage === 'en') ? savedLanguage : 'fr';
      setLanguageState(initialLanguage);
      localStorage.setItem('language', initialLanguage);
      setLoading(false);
    };

    loadLanguage();
  }, []);

  const setLanguage = async (newLanguage: Language) => {
    setLanguageState(newLanguage);
    localStorage.setItem('language', newLanguage);

    // Sauvegarder dans le backend
    try {
      await profileService.updatePreferences({ language: newLanguage });
    } catch (err) {
      console.warn('Impossible de sauvegarder la langue dans le backend:', err);
    }
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, loading }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

